# Use the official Nginx base image
FROM nginx:latest

# Copiar el archivo nginx.conf personalizado dentro del contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 (puerto por defecto de Nginx)
EXPOSE 80

# Comando para iniciar Nginx cuando se inicie el contenedor
CMD ["nginx", "-g", "daemon off;"]
